theme: jekyll-theme-minimal
title: The RPN-signature
description: by Tamas Spisak, Balint Kincses, Frederik Schlitt, Matthias Zunhammer, Tobias Schmidt-Wilcke, Zsigmond Tamas Kincses and Ulrike Bingel
logo: img/logo.png
google_analytics: UA-120757757-2
plugins:
  - jemoji
